image: maven:3.3.3-jdk-8
stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  only:
    - master
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
  tags:
    - docker

build_merge_job:
  stage: build
  except:
    - master
    - tags
  script:
    - git merge origin master --no-commit --no-ff
    - mvn --batch-mode compile -DskipTests=true -Djacoco.skip=true -U
  tags:
    - docker

test_sonar_preview_job:
  stage: test
  except:
    - master
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=incremental
  tags:
    - docker

test_sonar_job:
  stage: test
  only:
    - master
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.jdbc.url=$SONAR_DB -Dsonar.jdbc.username=$SONAR_USERNAME -Dsonar.jdbc.password=$SONAR_PASSWORD
  tags:
    - docker

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - mvn --batch-mode deploy -DskipTests=true -Djacoco.skip=true
  tags:
    - docker
